# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'tripplanner' do
	pod 'SnapKit', '~> 0.17.0'
    pod 'Alamofire', '~> 3.0'
    pod 'GoogleMaps'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'tripplannerTests' do

end

